# Generated by Django 2.0.4 on 2018-04-25 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherdata',
            name='certificates',
        ),
        migrations.RemoveField(
            model_name='teacherdata',
            name='subjects',
        ),
    ]
