# Generated by Django 2.0.4 on 2018-04-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_page', '0002_auto_20180425_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherdata',
            name='certificates',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='teacherdata',
            name='subjects',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
