# Generated by Django 2.0.4 on 2018-04-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_page', '0002_remove_teacherdata_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherdata',
            name='filename',
            field=models.FileField(default='none', upload_to=''),
        ),
    ]
