# Generated by Django 2.0.4 on 2018-04-30 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_page', '0003_auto_20180425_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherdata',
            name='DoB',
        ),
        migrations.RemoveField(
            model_name='teacherdata',
            name='HomeAddress',
        ),
        migrations.RemoveField(
            model_name='teacherdata',
            name='certificates',
        ),
        migrations.RemoveField(
            model_name='teacherdata',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teacherdata',
            name='pNumber',
        ),
        migrations.RemoveField(
            model_name='teacherdata',
            name='subjects',
        ),
    ]
