# Generated by Django 2.0.4 on 2018-04-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_page', '0004_auto_20180430_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherdata',
            name='DoB',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='teacherdata',
            name='HomeAddress',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='teacherdata',
            name='certificates',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='teacherdata',
            name='email',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='teacherdata',
            name='pNumber',
            field=models.CharField(default='none', max_length=13),
        ),
        migrations.AddField(
            model_name='teacherdata',
            name='subjects',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
