# Generated by Django 2.0.4 on 2018-05-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_page', '0004_auto_20180501_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherdata',
            name='experience',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='teacherdata',
            name='reference',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
