# Generated by Django 2.0.4 on 2018-05-23 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_page', '0006_remove_teacherdata_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherdata',
            name='subjects',
        ),
    ]
