# Generated by Django 2.0.4 on 2018-05-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_page', '0007_remove_teacherdata_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherdata',
            name='electric_guitar',
            field=models.BooleanField(default='False'),
        ),
    ]
