# Generated by Django 2.0.4 on 2018-05-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_page', '0009_auto_20180524_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherdata',
            name='cello',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='teacherdata',
            name='clarinet',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='teacherdata',
            name='drums',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='teacherdata',
            name='flute',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='teacherdata',
            name='piano',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='teacherdata',
            name='saxophone',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='teacherdata',
            name='violin',
            field=models.BooleanField(default='False'),
        ),
    ]
