# Generated by Django 2.0.4 on 2018-04-25 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginPage', '0002_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='instrument',
        ),
    ]
