# Generated by Django 2.0.4 on 2018-05-26 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginPage', '0004_account_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountManager',
        ),
    ]
