# Generated by Django 2.0.4 on 2018-05-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(default='none', max_length=200)),
                ('LastName', models.CharField(default='none', max_length=200)),
                ('UserName', models.CharField(default='none', max_length=20)),
                ('password', models.CharField(default='none', max_length=20)),
                ('GenderRadioOptions', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=5)),
                ('DoB', models.CharField(default='none', max_length=20)),
                ('HomeAddress', models.CharField(default='none', max_length=200)),
                ('Email', models.CharField(default='none', max_length=200)),
                ('pNumber', models.CharField(default='none', max_length=13)),
                ('subjects', models.CharField(default='none', max_length=200)),
                ('instrument', models.CharField(default='none', max_length=20)),
            ],
        ),
    ]
