# Generated by Django 2.0.4 on 2018-05-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='subjects',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
