# Generated by Django 2.0.4 on 2018-04-30 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdata',
            old_name='FullName',
            new_name='FirstName',
        ),
    ]
