# Generated by Django 2.0.4 on 2018-05-27 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdata',
            name='instrument',
        ),
    ]
