# Generated by Django 2.0.4 on 2018-05-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_account', '0002_remove_studentdata_instrument'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='instrument',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
