# Generated by Django 2.0.4 on 2018-05-27 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_account', '0002_studentdata_subjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdata',
            old_name='subjects',
            new_name='perferedsubjects',
        ),
    ]
