# Generated by Django 2.0.4 on 2018-04-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_account', '0002_auto_20180430_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdata',
            old_name='certificates',
            new_name='LastName',
        ),
        migrations.AddField(
            model_name='studentdata',
            name='GenderRadioOptions',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='password',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='FirstName',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
