# Generated by Django 2.0.4 on 2018-04-30 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_account', '0003_auto_20180501_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdata',
            old_name='email',
            new_name='Email',
        ),
    ]
