# Generated by Django 2.0.4 on 2018-05-27 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_account', '0003_auto_20180528_0119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdata',
            old_name='perferedsubjects',
            new_name='preferredSubjects',
        ),
    ]
