# Generated by Django 2.0.4 on 2018-04-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_account', '0004_auto_20180501_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='GenderRadioOptions',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
