# Generated by Django 2.0.4 on 2018-05-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_account', '0006_remove_studentdata_genderradiooptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='GenderRadioOptions',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default=2, max_length=5),
            preserve_default=False,
        ),
    ]
