# Generated by Django 2.0.4 on 2018-05-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_account', '0008_auto_20180501_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='GenderRadioOptions',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='none', max_length=5),
        ),
    ]
