# Generated by Django 2.0.4 on 2018-05-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_account', '0012_auto_20180513_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='pFirstName',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='pLastName',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
