# Generated by Django 2.0.4 on 2018-05-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_account', '0013_auto_20180515_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='pEmail',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='parentsNumber',
            field=models.CharField(default='none', max_length=13),
        ),
    ]
