# Generated by Django 2.0.4 on 2018-05-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_account', '0015_auto_20180520_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='DoB',
            field=models.DateField(blank=True, null=True),
        ),
    ]
