# Generated by Django 2.0.4 on 2018-05-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cello_half_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='cello_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='clarinet_half_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='clarinet_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(default='none', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='drums_half_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='drums_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='electric_guitar_half_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='electric_guitar_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='flute_half_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='flute_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='guitar_half_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='guitar_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='keyboard_half_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='keyboard_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='pendingLessonContracts_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='none', max_length=200)),
                ('last_name', models.CharField(default='none', max_length=200)),
                ('contract_period', models.CharField(default='none', max_length=10)),
                ('instrument', models.CharField(default='none', max_length=200)),
                ('time', models.CharField(default='none', max_length=20)),
                ('day', models.CharField(default='none', max_length=20)),
                ('timePeriod', models.CharField(default='none', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='pendingLessonContracts_old',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='none', max_length=200)),
                ('last_name', models.CharField(default='none', max_length=200)),
                ('contract_period', models.CharField(default='none', max_length=10)),
                ('instrument', models.CharField(default='none', max_length=200)),
                ('time1', models.CharField(default='none', max_length=20)),
                ('time2', models.CharField(default='none', max_length=20)),
                ('time3', models.CharField(default='none', max_length=20)),
                ('day1', models.CharField(default='none', max_length=20)),
                ('day2', models.CharField(default='none', max_length=20)),
                ('day3', models.CharField(default='none', max_length=20)),
                ('timePeriod1', models.CharField(default='none', max_length=20)),
                ('timePeriod2', models.CharField(default='none', max_length=20)),
                ('timePeriod3', models.CharField(default='none', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months', models.CharField(default='none', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='piano_half_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='piano_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='saxophone_half_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='saxophone_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='violin_half_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='violin_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.TimeField()),
            ],
        ),
    ]
