# Generated by Django 2.0.4 on 2018-05-26 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessonBooking', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViolinHourTimes',
        ),
    ]
