# Generated by Django 2.0.4 on 2018-05-29 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessonBooking', '0003_delete_testing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pendingLessonContracts_new',
        ),
        migrations.DeleteModel(
            name='pendingLessonContracts_old',
        ),
    ]
