# Generated by Django 2.0.4 on 2018-05-26 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessonBooking', '0003_electric_guitar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='electric_guitar',
            new_name='electric_guitar_hour',
        ),
    ]
