# Generated by Django 2.0.4 on 2018-05-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonBooking', '0004_auto_20180529_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='pendingLessonContracts_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='none', max_length=200)),
                ('last_name', models.CharField(default='none', max_length=200)),
                ('contract_period', models.CharField(default='none', max_length=10)),
                ('instrument', models.CharField(default='none', max_length=200)),
                ('time', models.CharField(default='none', max_length=20)),
                ('day', models.CharField(default='none', max_length=20)),
                ('timePeriod', models.CharField(default='none', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='pendingLessonContracts_old',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='none', max_length=200)),
                ('last_name', models.CharField(default='none', max_length=200)),
                ('contract_period', models.CharField(default='none', max_length=10)),
                ('instrument', models.CharField(default='none', max_length=200)),
                ('time1', models.CharField(default='none', max_length=20)),
                ('time2', models.CharField(default='none', max_length=20)),
                ('time3', models.CharField(default='none', max_length=20)),
                ('day1', models.CharField(default='none', max_length=20)),
                ('day2', models.CharField(default='none', max_length=20)),
                ('day3', models.CharField(default='none', max_length=20)),
                ('timePeriod1', models.CharField(default='none', max_length=20)),
                ('timePeriod2', models.CharField(default='none', max_length=20)),
                ('timePeriod3', models.CharField(default='none', max_length=20)),
            ],
        ),
    ]
