# Generated by Django 2.0.4 on 2018-05-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonBooking', '0006_auto_20180526_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='pendingLessonContracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='none', max_length=200)),
                ('last_name', models.CharField(default='none', max_length=200)),
            ],
        ),
    ]
