# Generated by Django 2.0.4 on 2018-05-27 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessonBooking', '0007_pendinglessoncontracts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendinglessoncontracts',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='pendinglessoncontracts',
            name='last_name',
        ),
    ]
