# Generated by Django 2.0.4 on 2018-05-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonBooking', '0009_auto_20180527_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(default='none', max_length=10)),
            ],
        ),
    ]
