# Generated by Django 2.0.4 on 2018-05-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonBooking', '0011_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinglessoncontracts',
            name='time',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
