# Generated by Django 2.0.4 on 2018-05-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessonBooking', '0012_auto_20180528_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='pendingLessonContracts_old',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='none', max_length=200)),
                ('last_name', models.CharField(default='none', max_length=200)),
                ('instrument', models.CharField(default='none', max_length=200)),
                ('time1', models.CharField(default='none', max_length=20)),
                ('time2', models.CharField(default='none', max_length=20)),
                ('time3', models.CharField(default='none', max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='pendingLessonContracts',
            new_name='pendingLessonContracts_new',
        ),
    ]
